"""Tabela oficial de países / códigos do SIBA ("Tabela ICAO").

Fonte: SIBA -> Ajuda -> Modos de Envio -> Lista de Países / Códigos ICAO
       https://siba.ssi.gov.pt/ajuda/modos-de-envio/lista-de-paises/

ATENÇÃO: estes códigos NÃO são todos iguais ao ISO 3166-1 alpha-3. O caso mais
notório é a Alemanha, cujo código no SIBA é "D" (uma só letra) e não "DEU".
Só são aceites pelo portal os códigos desta tabela — usar outra codificação
(ex.: ISO) faz o boletim ser rejeitado ("Nacionalidade inválida").

Para acrescentar/corrigir, editar o dicionário PAISES (código -> designação).
"""

from __future__ import annotations

import unicodedata

# código SIBA -> designação (a mostrar no dropdown). Ordenado por nome no dropdown.
PAISES: dict[str, str] = {
    "AFG": "AFEGANISTÃO",
    "ALB": "ALBÂNIA",
    "DZA": "ARGÉLIA",
    "AND": "ANDORRA",
    "AGO": "ANGOLA",
    "ATG": "ANTÍGUA E BARBUDA",
    "ARG": "ARGENTINA",
    "ARM": "ARMÉNIA",
    "AUS": "AUSTRÁLIA",
    "AUT": "ÁUSTRIA",
    "AZE": "AZERBAIJÃO",
    "BHS": "BAHAMAS",
    "BHR": "BARÉM",
    "BGD": "BANGLADESH",
    "BRB": "BARBADOS",
    "BLR": "BIELORRÚSSIA",
    "PLW": "PALAU",
    "BEL": "BÉLGICA",
    "BLZ": "BELIZE",
    "BEN": "BENIM",
    "BMU": "BERMUDAS",
    "BTN": "BUTÃO",
    "BOL": "BOLÍVIA",
    "BIH": "BÓSNIA HERZEGOVINA",
    "BWA": "BOTSWANA",
    "BRA": "BRASIL",
    "BRN": "BRUNEI DARUSSALAM",
    "BGR": "BULGÁRIA",
    "BFA": "BURKINA FASO",
    "MMR": "MYANMAR",
    "BDI": "BURUNDI",
    "KHM": "CAMBOJA",
    "CMR": "CAMARÕES",
    "CAN": "CANADÁ",
    "CPV": "CABO VERDE",
    "CAF": "REP. CENTRO AFRICANA",
    "TCD": "CHADE",
    "CHL": "CHILE",
    "CHN": "CHINA",
    "COL": "COLOMBIA",
    "COM": "COMORES",
    "COG": "CONGO",
    "COK": "ILHAS COOK",
    "CRI": "COSTA RICA",
    "HRV": "CROÁCIA",
    "CZE": "REPÚBLICA CHECA",
    "CUB": "CUBA",
    "CYP": "CHIPRE",
    "DNK": "DINAMARCA",
    "DJI": "JIBUTI",
    "DMA": "DOMINICA",
    "DOM": "REPÚBLICA DOMINICANA",
    "TLS": "TIMOR-LESTE",
    "ECU": "EQUADOR",
    "EGY": "EGIPTO",
    "SLV": "EL SALVADOR",
    "GNQ": "GUINÉ EQUATORIAL",
    "ERI": "ERITREIA",
    "EST": "ESTÓNIA",
    "ETH": "ETIÓPIA",
    "FJI": "ILHAS FIJI",
    "FIN": "FINLÂNDIA",
    "FRA": "FRANÇA",
    "GAB": "GABÃO",
    "GMB": "GÂMBIA",
    "GEO": "GEÓRGIA",
    "D": "ALEMANHA",
    "GHA": "GANA",
    "GRC": "GRÉCIA",
    "GRD": "GRANADA",
    "GUM": "GUAM",
    "GTM": "GUATEMALA",
    "GIN": "GUINÉ",
    "GNB": "GUINÉ-BISSAU",
    "GUY": "GUIANA",
    "HTI": "HAITI",
    "HND": "HONDURAS",
    "HKG": "HONG KONG",
    "HUN": "HUNGRIA",
    "ISL": "ISLANDIA",
    "IND": "ÍNDIA",
    "IDN": "INDONÉSIA",
    "IRN": "IRÃO",
    "IRQ": "IRAQUE",
    "IRL": "IRLANDA",
    "ISR": "ISRAEL",
    "ITA": "ITÁLIA",
    "CIV": "COSTA DO MARFIM",
    "JAM": "JAMAICA",
    "JPN": "JAPÃO",
    "JOR": "JORDANIA",
    "KAZ": "CAZAQUISTÃO",
    "KEN": "QUÉNIA",
    "KIR": "KIRIBATI",
    "PRK": "COREIA DO NORTE",
    "KOR": "COREIA DO SUL",
    "RKS": "KOSOVO",
    "KWT": "KUWAIT",
    "KGZ": "QUIRGUIZISTÃO",
    "LAO": "LAOS",
    "LVA": "LETÓNIA",
    "LBN": "LÍBANO",
    "LSO": "LESOTO",
    "LBR": "LIBÉRIA",
    "LBY": "LÍBIA",
    "LIE": "LIECHTENSTEIN",
    "LTU": "LITUANIA",
    "LUX": "LUXEMBURGO",
    "MAC": "MACAU",
    "MKD": "MACEDÓNIA DO NORTE",
    "MDG": "MADAGÁSCAR",
    "MWI": "MALAWI",
    "MYS": "MALÁSIA",
    "MDV": "MALDIVAS",
    "MLI": "MALI",
    "MLT": "MALTA",
    "MHL": "ILHAS MARSHALL",
    "MRT": "MAURITÂNIA",
    "MUS": "MAURÍCIAS",
    "MYT": "MAYOTTE",
    "MEX": "MÉXICO",
    "FSM": "MICRONÉSIA",
    "MDA": "MOLDÁVIA",
    "MCO": "MÓNACO",
    "MNG": "MONGÓLIA",
    "MSR": "MONSERRATE",
    "MNE": "MONTENEGRO",
    "MAR": "MARROCOS",
    "MOZ": "MOÇAMBIQUE",
    "NAM": "NAMÍBIA",
    "NRU": "NAURU",
    "NPL": "NEPAL",
    "NLD": "PAÍSES BAIXOS",
    "NCL": "NOVA CALEDÓNIA",
    "NZL": "NOVA ZELÂNDIA",
    "NIC": "NICARÁGUA",
    "NER": "NÍGER",
    "NGA": "NIGÉRIA",
    "NIU": "NIUE",
    "NOR": "NORUEGA",
    "OMN": "OMAN",
    "PAK": "PAQUISTÃO",
    "PSE": "PALESTINA",
    "PAN": "PANAMÁ",
    "PNG": "PAPUÁSIA NOVA GUINÉ",
    "PRY": "PARAGUAI",
    "PER": "PERU",
    "PHL": "FILIPINAS",
    "POL": "POLÓNIA",
    "PRT": "PORTUGAL",
    "PRI": "PORTO RICO",
    "QAT": "CATAR",
    "COD": "REP. DEMOCRÁTICA CONGO",
    "REU": "REUNIÃO",
    "ROU": "ROMÉNIA",
    "RUS": "RÚSSIA",
    "RWA": "RUANDA",
    "STP": "SÃO TOMÉ PRÍNCIPE",
    "VCT": "SÃO VICENTE E GRANADINAS",
    "WSM": "SAMOA",
    "SMR": "SÃO MARINO",
    "SAU": "ARÁBIA SAUDITA",
    "SEN": "SENEGAL",
    "SRB": "SÉRVIA",
    "SYC": "SEYCHELLES",
    "SLE": "SERRA LEOA",
    "SGP": "SINGAPURA",
    "SVK": "REPÚBLICA ESLOVACA",
    "SVN": "ESLOVÉNIA",
    "SLB": "ILHAS SALOMÃO",
    "SOM": "SOMÁLIA",
    "ZAF": "ÁFRICA DO SUL",
    "SSD": "SUDÃO DO SUL",
    "ESP": "ESPANHA",
    "LKA": "SRI LANCA",
    "KNA": "SÃO CRISTÓVÃO E NEVIS",
    "LCA": "SANTA LÚCIA",
    "SDN": "SUDÃO",
    "SUR": "SURINAME",
    "SWZ": "SUAZILÂNDIA",
    "SWE": "SUÉCIA",
    "CHE": "SUÍÇA",
    "SYR": "SÍRIA",
    "TWN": "TAIWAN",
    "TJK": "TAJIQUISTÃO",
    "TZA": "TANZÂNIA",
    "THA": "TAILÂNDIA",
    "TGO": "TOGO",
    "TON": "TONGA",
    "TTO": "TRINDADE E TOBAGO",
    "TUN": "TUNÍSIA",
    "TUR": "TURQUIA",
    "TKM": "TURQUEMENISTÃO",
    "TUV": "TUVALU",
    "UGA": "UGANDA",
    "UKR": "UCRANIA",
    "ARE": "EMIRATOS ÁRABES UNIDOS",
    "GBR": "REINO UNIDO",
    "URY": "URUGUAI",
    "USA": "E. U. AMÉRICA",
    "UZB": "USBEQUISTÃO",
    "VUT": "VANUATU",
    "VAT": "SANTA SÉ",
    "VEN": "VENEZUELA",
    "VNM": "VIETNAME",
    "YEM": "IÉMEN",
    "ZMB": "ZAMBIA",
    "ZWE": "ZIMBABWE",
}


def _sem_acentos(texto: str) -> str:
    """Chave de ordenação alfabética do dropdown (ignora acentos)."""
    return "".join(
        c for c in unicodedata.normalize("NFKD", texto)
        if not unicodedata.combining(c)
    )


def nome_pais(codigo: str) -> str:
    """Devolve o nome do país para um código, ou o próprio código se desconhecido."""
    return PAISES.get((codigo or "").strip().upper(), codigo)


def lista_ordenada() -> list[tuple[str, str]]:
    """Lista de (codigo, nome) ordenada por nome, para preencher dropdowns."""
    return sorted(PAISES.items(), key=lambda kv: _sem_acentos(kv[1]))


def valido(codigo: str) -> bool:
    return (codigo or "").strip().upper() in PAISES
